WITH RECURSIVE HOUR24 AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM HOUR24
    WHERE HOUR < 23)
SELECT h.HOUR, (SELECT COUNT(*)
               FROM ANIMAL_OUTS
               WHERE HOUR(DATETIME) = h.HOUR) AS COUNT
FROM HOUR24 h