# -- 코드를 작성해주세요
# SELECT A.ID, B.FISH_NAME, A.LENGTH
# FROM FISH_INFO A JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
# WHERE A.LENGTH IN (SELECT MAX(LENGTH)
#                   FROM FISH_INFO
#                   WHERE FISH_TYPE = B.FISH_TYPE)


SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
WHERE I.LENGTH IN (SELECT MAX(LENGTH)
                  FROM FISH_INFO
                  WHERE FISH_TYPE = N.FISH_TYPE)