-- 코드를 입력하세요
# SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
# FROM ICECREAM_INFO A JOIN FIRST_HALF B ON A.FLAVOR = B.FLAVOR
# GROUP BY INGREDIENT_TYPE
# ORDER BY TOTAL_ORDER

SELECT I.INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF F JOIN ICECREAM_INFO I ON F.FLAVOR = I.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER 